### PR TITLE
Improve coverage

### PR DESCRIPTION
**Pull request by abe33**

### CODE REVIEW

**Comment by jansorg** [comment]
@abe33 The PyCharm plugin doesn't handle use kited's status flag to suppress requests. Do you mind if we move these test into folder which are only used by Atom and VSCode for now?

**Comment by abe33** [comment]
With the current version of master (which this branch is based on) I don't we have a way to isolate tests per editor, we'll have to merge the other PR first, so that all runners can filter the tests. 
Also, maybe it's Atom behaviour which is wrong here, maybe I shouldn't check the status before making requests? (as I'm knowing if kite is not installed/running/reachable with the focus event, every other features can be deactivated)

**Comment by jansorg** [comment]
I'm not sure atm what behaviour is correct. 
Afaik nodejs can't set a timeout to requests. Requests to an unconnected endpoint (i.e. kite not running) will take a long time to finish (this is on Windows only, I think). Do you know if this is still the case?
PyCharm has short timeouts here to make sure that hover, event, etc. don't block.

**Comment by abe33** [comment]
We do have timeouts on requests in node, of course, but that's not thanks to the timeout we can detect when kite is not running (a timeout generally occurs if the server doesn't respond something  while the handshake was still ok)

**Pull request merged**
