### PR TITLE
Create json tests for the new completion spec

### PR DESCRIPTION
**Pull request by jansorg**
The tests follow the spec at https://kite.quip.com/LVIZAGwNQKEg/Spec-Code-Completions-Editor-Plugins-UIUX-WIP#STDACAkLzia .
- Updates `atom.json` file
- Copied `default.json` to `vscode.json` and adds the directories of the new set of supported spec

### CODE REVIEW

**Comment by jansorg** [comment]
@abe33 Thanks for the helpful feedback!
I've cleaned up the file and directory names. Let me know if there's still something unexpected.

The all/dot/... tests follow the section of the spec at https://kite.quip.com/LVIZAGwNQKEg/Spec-Code-Completions-Editor-Plugins-UIUX-WIP#STDACAkLzia to make it easier to match file and the part of the spec when updates are necessary later on.

**Comment by abe33** [comment]
@jansorg I was just guessing based on the tests I saw listed for atom, but I may have been confused because now that I look closer the `continuous/completion_newline.json` tests don't concern Atom, right?

**Comment by abe33** [comment]
BTW, I ran the new tests in atom and the ones currently failing are for `"` and `'`.

**Comment by jansorg** [comment]
@abe33 I've updated the last failing test and the speec to make this pass in VSCode. Could you check if this is the case now, please?

**Pull request merged**
